sudo: required
language: go
dist: xenial

go:
- 1.12.7

before_script:
  - git clone --depth 1 -b "v0.6.1" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh

script:
  - ./ci.sh ./1_internals
  - ./ci.sh ./2_authorization
  - ./ci.sh ./4_computational_resources
