sudo: required
language: go
dist: bionic 

go:
- 1.13.5

before_script:
  - git clone --depth 1 -b "v0.7.0-2" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh -c
  - ./kind-travis-ci/helm-install.sh

script:
  - ./1_internals/ci.sh
  - ./2_authorization/ci.sh
  - ./3_policies/ci.sh
  - ./4_computational_resources/ci.sh
