apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: k8s-school/kubectl-proxy1.15.3
